### PR TITLE
ansible working on centos

### PR DESCRIPTION
**Pull request by jeffbean**
Added: Vagrantfile to test CentOS provisioning.

New variable for kube cert directory.
Moved default vars from master and node role to kubernetes role since they are the same values right now.
Moved some cert tasks into kubernetes role to fit both nodes and masters

This change fixes issues with group and user variability on certs and services.

### CODE REVIEW

**Comment by eparis** [comment]
ok, i'm going to hack on this a little more.  So I'm going to rebase under you, merge, generally screw you up, if you don't mind....

**Comment by eparis** [comment]
So I'm going to push a new branch.  I tried to take all of your ideas, and rework them again. You'll have to tell me what you think.  Basically I'm generating the certs on master[0]. But instead of fetching them I'm only fetching and ssh pub key from master[0], sending that to all the nodes, then copying the certs directly from master->node.  I wish ansible had a better way to do this....

**Comment by eparis** [comment]
I undid the token changes. I expect people to run the full playbook at least once...  I don't want a single run with --tags=certs to undo the token stuff they did in a previous playbook run...

**Comment by jeffbean** [comment]
OK Great stuff.  

What state are you in? What do you need from me at this point? Do you need me to fix this pull request to merge in?

**Pull request closed without merging**
